### ISSUE TITLE
Lots of index.php errors

### ISSUE THREAD

**Issue by Vaults1** [BoxOfDevs/BoxManager#10]
This user acknowledges that:
- [x] The issue, is actually an issue
- [x] It is a BoxManager problem
- [x] The code has not been edited.
- [x] The issue contains appropriate markdown (e.g code blocks for code)

# Description

Warning: scandir(resources/): failed to open dir: No such file or directory in /storage/emulated/0/htdocs/manager/BoxManager-master/index.php on line 46

Warning: scandir(): (errno 2): No such file or directory in /storage/emulated/0/htdocs/manager/BoxManager-master/index.php on line 46

Warning: array_diff(): Argument #1 is not an array in /storage/emulated/0/htdocs/manager/BoxManager-master/index.php on line 46

Warning: Invalid argument supplied for foreach() in /storage/emulated/0/htdocs/manager/BoxManager-master/index.php on line 46

Warning: scandir(/storage/emulated/0/htdocs/manager/BoxManager-master/resources): failed to open dir: No such file or directory in /storage/emulated/0/htdocs/manager/BoxManager-master/index.php on line 124

Warning: scandir(): (errno 2): No such file or directory in /storage/emulated/0/htdocs/manager/BoxManager-master/index.php on line 124

Warning: array_diff(): Argument #1 is not an array in /storage/emulated/0/htdocs/manager/BoxManager-master/index.php on line 124

Warning: Invalid argument supplied for foreach() in /storage/emulated/0/htdocs/manager/BoxManager-master/index.php on line 124
# Server specs

PHP version: 5
MySQL version:
# Additional info (optional)

This just might be my android localhoster...

**Comment by Ad5001** [comment]
Try downloading the new files, fixed them...
