### ISSUE TITLE
Can I help??

### ISSUE THREAD

**Issue by lavender-sys** [BoxOfDevs/BoxManager#11]
I could work on small things.

**Comment by lavender-sys** [comment]
Also, where's the testing site?

**Comment by Vaults1** [comment]
1. You can fork the project and make a PR. 👍 If you want to join the team you'll have to ask @TheDragonRing 
2. I'm not sure if we have one. 👅

**Comment by lavender-sys** [comment]
theres ad5001.ga/BOxManager but thats broken

**Comment by Ad5001** [comment]
Yup need to update it.

**Comment by lavender-sys** [comment]
Im running commit 1860247c9fe8e2179f9646199d69ba0b79448ddb and it has a 500 error.

**Comment by Ad5001** [comment]
I have setted up an Online server locally, and the errors are about sessions.

**Comment by lavender-sys** [comment]
Okay. Can you fix it please??

**Comment by Ad5001** [comment]
That is ... pretty hard

**Comment by lavender-sys** [comment]
:(

**Comment by Ad5001** [comment]
Because we need to change the whoole login system.

**Comment by lavender-sys** [comment]
But it would have to be fixed sometime. Otherwise, BoxManager would never be done.

**Comment by dragonwocky** [comment]
@Dog2puppy can join, I meant to get around to inviting him ages ago.... I seriously need to get BoxOfDevs back into shape...
