### ISSUE TITLE
Notice: Signup page broken.

### ISSUE THREAD

**Issue by Vaults1** [BoxOfDevs/BoxManager#3]
I am working on a fix, also, maybe add some CSS to it, it will look nicer. 😄

**Comment by Ad5001** [comment]
Where ?

**Comment by Vaults1** [comment]
I think it's fixed.

**Comment by Vaults1** [comment]
Hang on, it isn't.

**Comment by Ad5001** [comment]
Sign up page works just fine for me http://ad5001.ga/BoxManager/signup/index.php

**Comment by Vaults1** [comment]
Update: May be fixed, please test.

**Comment by Ad5001** [comment]
There are some conflict issues with head and origin\master

**Comment by Ad5001** [comment]
http://ad5001.ga/BoxManager/signup/register.php here you can test it but seems still broken because it always shows an error on register

**Comment by Ad5001** [comment]
Is this is issue still up to date?
