### ISSUE TITLE
Parse error: syntax error, unexpected end of file in index.php on line 51

### ISSUE THREAD

**Issue by Vaults1** [BoxOfDevs/BoxManager#7]
This user acknowledges that:
- [x] The issue, is actually an issue
- [x] This is a BoxManager problem
- [x] The code has not been edited.
- [x] The issue contains appropriate markdown (e.g code blocks for code)

# Description

Parse error: syntax error, unexpected end of file in index.php on line 51
# Server specs

PHP version: 5
MySQL version: N/A
# Additional info (optional)

Strangely, there is no line 51. This happened after I fixed #6.

**Comment by Ad5001** [comment]
Ok will start on it soon.

**Comment by Ad5001** [comment]
Which index.php?

**Comment by Ad5001** [comment]
Erm... This is normal ! I used a multiline string but you just deleted the end :S Readded it+ fixing #6
