### ISSUE TITLE
Security?

### ISSUE THREAD

**Issue by Ad5001** [BoxOfDevs/BoxManager#8]
This user acknowledges that:
- [x] The issue, is actually an issue
- [x] It is a BoxManager problem
- [x] The code has not been edited.
- [ ] The issue contains appropriate markdown (e.g code blocks for code)

# Description

Having looked at the security, the database is only saved in md5 ! we should really take a new hash to make it more secure (like my custom hash that I made or sha256
# Server specs

PHP version:
7.0.10
MySQL version:
3
# Additional info (optional)

**Comment by Vaults1** [comment]
I was also concerned about security.

**Comment by Ad5001** [comment]
Yeah, might do a replace in all files of md5 by sha256
But I don't kow if I should upload my ow custom hash that ismore securised but might have some problems in the algorithm...

**Comment by Vaults1** [comment]
sha256 and md5 can still be cracked quickly, I think we should work on security. I was thinking that uploaded files should go through an antivirus check.

**Comment by Ad5001** [comment]
If you look at the way I handled the file upload....

**Comment by Ad5001** [comment]
I don't think it's possible to do this (exept if the owner accept shell script wich would seems stupid...)

**Comment by Ad5001** [comment]
But I like theidea of the antivirus but: Since our work is free, it's easily hackable so hackers can test their hacks on it...

**Comment by ghost** [comment]
Solution: Use a 256 Bit SSL Certificate

**Comment by Vaults1** [comment]
@KairusDarkSeeker doesn't that mean every user will have to buy one?
@Ad5001 What about phpass hashes?

**Comment by Ad5001** [comment]
Could be an idea....

**Comment by ghost** [comment]
We're making this for free, if this is not free they can have security plus use [Cloudflare](https://cloudflare.com) if you want a better security

**Comment by ghost** [comment]
Or use SimpleAuth's sha512 Hash with salt because its licensed as GNU so its free for anyone to use or redistribute with the license

**Comment by Ad5001** [comment]
Ikr, but I'm gona make a multiple encryption at the same time -> http://php.net/book/function.hash.php

**Comment by ghost** [comment]
use password_hash() and password_verify() rather than finding any encryption methods

**Comment by Ad5001** [comment]
Done. Changed to sha512
