### ISSUE TITLE
PHPClassMailer seems to have some isseus wih sessions

### ISSUE THREAD

**Issue by Ad5001** [BoxOfDevs/BoxManager#9]
This user acknowledges that:
- [x] The issue, is actually an issue
- [x] It is a BoxManager problem
- [x] The code has not been edited.
- [x] The issue contains appropriate markdown (e.g code blocks for code)

# Description

-> Error broadcasted before the nav BUT after the <html> tag
-> This is an error related to sessions. when we use CheckLogin. BUT I have callled this method BEFORE putting the <html> tag
-> Error:  Warning: session_start(): Cannot send session cookie - headers already sent by (output started at _PRIVATE_\plugins\Online\BoxManager\login\class.phpmailer.php:1911) in _PRIVATE_\plugins\Online\BoxManager\login\fg_membersite.php on line 133
# Server specs

PHP version: 7.0.10
MySQL version: 5.0.29
# Additional info (optional)

**Comment by Vaults1** [comment]
I forwarded it to PHPMAILER.

**Comment by Ad5001** [comment]
Ok

**Comment by Ad5001** [comment]
Ok

**Comment by Vaults1** [comment]
What version of PHP mailer are we running?

**Comment by Ad5001** [comment]
I updated and it doesn't seems to be from PHPMailer anymore.

**Comment by Vaults1** [comment]
Our version of PHPMailer is from **_2008_**. Problem solved.

**Comment by Ad5001** [comment]
LOL Did you download it with the login system (because I had to fix a lot errors
from it x) )
